-- Create the comments table if it doesn't exist
create table if not exists comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  content text not null
);

-- Enable Row Level Security (RLS)
alter table comments enable row level security;

-- Create policies for anonymous access (since we don't have auth yet)
-- 1. Allow everyone to read comments
create policy "Enable read access for all users"
on comments for select
using (true);

-- 2. Allow everyone to insert comments
create policy "Enable insert access for all users"
on comments for insert
with check (true);

-- 3. Allow everyone to delete comments (Warning: Insecure for production, fine for demo)
-- Ideally, you'd only allow users to delete their own comments via Auth.
create policy "Enable delete access for all users"
on comments for delete
using (true);
